### ISSUE TITLE
Support Upload New Version in Content Explorer

### ISSUE THREAD

**Issue by sghosh326** [box/box-ui-elements#140]
Support file versioning and the "Upload New Version" feature that is in the Box application in the Content Explorer UI Element

**Comment by tonyjin** [comment]
Thanks for the request. We'll consider this feature during planning.

**Comment by briangleeson** [comment]
+1 this would be a useful feature

**Comment by sghosh326** [comment]
When I look through the releases page, I see Issue #220 that was pushed in release 4.4.0 and it appears that the feature shows a file's version history in the Content Sidebar component. How is the Content Sidebar used in conjunction with Content Explorer? Does the Content Sidebar shows the details about a selected file similar to Box app. Is there any documentation on using the Content Sidebar component?

**Comment by tonyjin** [comment]
@sghosh326 the Content Sidebar is in development and not ready for public consumption yet. We anticipate a public launch in Q3 (Aug - Oct). Also, the functionality you're alluding to doesn't quite map to this issue since this is referring to the ability to upload new versions.

**Comment by sghosh326** [comment]
@tonyjin thanks for your response. We have made a lot of mods to the code in our fork and I know the code very well. I just want to know as a developer how to use the Content Sidebar in conjunction with Content Explorer. 
For me to add an "Upload New Version" menu item to a selected item menu for files is no big deal and I can also add the "V1", "V2" label next to the file name. I was hoping to use the Content Sidebar to list the versions of the file and have a link to preview previous versions. This would be in lieu of Box Version dialog which would be complicated to build.

**Comment by tonyjin** [comment]
Awesome! I'm glad you're deep in the code. We're currently aiming to have the Content Sidebar be at parity with the preview sidebar you see in the main web application. While the current version dialog won't be directly implemented in the sidebar right now (it'll be a callback passed in by our main application), we're exploring different ways to add an embedded version history experience into the sidebar.

What we're currently building won't necessarily provide the experience you're looking for since the activity feed (the tab with comments & versions) may combine version history updates (e.g. `X uploaded versions 1-3`).

When the Content Sidebar is complete, it'll be both be usable by itself and be embedded in the ContentPreview Element so you won't much additional work to hook it up in the Content Explorer (since the Content Explorer includes ContentPreview which will include ContentSidebar).

**Comment by sghosh326** [comment]
Thanks Tony, I will handle the upload new version side of things now and wait for Version history in the Content Sidebar/Content Preview to be available to preview/download previous versions.
