### ISSUE TITLE
How to show document Version History in UI Content Explorer

### ISSUE THREAD

**Issue by mremigio** [box/box-ui-elements#199]
Hello:

How do we enable showing the document's  Version History on the UI Content Explorer ?
Is there an option ?  Does it have to be specified in the token ?  

Thanks
Mila

**Comment by priyajeet** [comment]
Version history is a feature coming up and will be seen in preview. So likely in a quarter.

**Comment by mremigio** [comment]
Thanks Priyajeet.  Will the feature include showing the name of the user that uploaded the document ?
I'm asking because this is a very important feature for our customers here at UCLA.

**Comment by tonyjin** [comment]
We're trying to build a popup similar to what you see in the Box WebApp: 
![2018-03-13_12-48-43](https://user-images.githubusercontent.com/689351/37366169-ea050ab6-26bc-11e8-9527-745fe078a5ad.png)

However, in V1 we're leaning towards only enabling popups triggered by the parent application (a callback passed into the ContentPreview Element that will show the popup) since we aren't sure that our component should be triggering modals in the parent application.

Specifically about the uploader name, that information will be available in the sidebar (see screenshot underneath the modal). We don't have a public release date for the sidebar yet, but I'll share when we have one.

**Comment by mremigio** [comment]
Hi Priyajeet and tonyjin:

Just wondering if this feature is available ?    If it is available, is it available in the JavaScript Agnostic libraries ?

Thanks

Mila

**Comment by priyajeet** [comment]
This feature is not yet available, we will comment and close this issue when it is available for use. Unfortunately no ETA yet.

**Comment by mremigio** [comment]
Thank you for the feedback priyajeet.   Our customers here at UCLA are very excited to see this feature.

**Comment by mremigio** [comment]
Hello:

When will this feature be available ?
We, here at UCLA, are anxiously waiting for this feature.

Thank you

**Comment by mremigio** [comment]
Hi Box UI Team:

What's the ETA on this feature ?
Thank you

**Comment by ConradJChan** [comment]
Hi @mremigio, for feature requests and ideas you can check out https://pulse.box.com/forums/909778-help-shape-the-future-of-box to provide your feedback.

**Comment by ConradJChan** [comment]
Also found this in the forum: https://community.box.com/t5/Box-Product-Updates/Preview-older-versions/idi-p/72385
