### ISSUE TITLE
Content explorer

### ISSUE THREAD

**Issue by dprosper** [box/box-ui-elements#212]
I would like to be able to use the ContentExplorer component for a folder that I am making 'public', i.e. accessible if you know the URL.  The UI elements require a token to be passed, so I am not really sure how to do that with that requirement.  If it is doable, can you provide an example?

**Comment by tonyjin** [comment]
Hi @dprosper this is possible today two different ways:

- Build a simple service that manages tokens and refreshes for a single folder and passes it to the ContentExplorer
- Use New Box View (https://developer.box.com/docs/getting-started-with-new-box-view) to generate a permanent access token and use that token to upload files and then view those files with the Content Explorer. This, however, means your token is on the client and a malicious user could then use that token to delete or upload other files.

Later this year, we'll be exploring integrating the ContentExplorer with Box open shared links, so that may be another route.

**Comment by dprosper** [comment]
Great I will look at the Box View option, any starter code example for the first option?

**Comment by tonyjin** [comment]
Please reach out to Box Support for help with option 1: https://support.box.com
