### ISSUE TITLE
Cannot use language property of ContentExplorer in Angular

### ISSUE THREAD

**Issue by timvdh** [box/box-ui-elements#3531]
This is how we use ContentExplorer, but we use V19.0.0 of the npm package:

https://github.com/SowaProgramuje/angular-box-ui-elements/blob/main/src/app/box-content-explorer/box-content-explorer.component.ts

I am setting the language property of the ContentExplorer to "de-DE", so the only change is:

```
contentExplorer.show(this.folderId, environment.BoxDeveloperToken, {
      container: '#box-content-explorer',
      language: 'de-DE'
});
```

But the display language is still English.

**Comment by greg-in-a-box** [comment]
I dont think changing the `language` property actually switches the the languages since the messages arent bundled within the component itself, you can provide the `messages` property by passing in the data from the properties files in the i18n folder

https://github.com/box/box-ui-elements/blob/0d1e9cfc83bd7bb2e49b64deb2e8cf35996334ed/i18n/de-DE.properties#L606
shown like this and it should reflect the translations
![image](https://github.com/box/box-ui-elements/assets/103291617/ee622a3a-d032-4f0d-9169-a2dd522993f2)

**Comment by timvdh** [comment]
Thank you, you are right of course... I thought the messages property was for custom translations only. I included the i18n/*.js files in the assets folder and I can dynamically import a desired language file with

`const module = await import(`../../assets/${this.locale}.js`);`

and set the messages property to module.default. What I did not manage was to import the i18n/*.js file via assets configuration in angular.json, so I have to copy them manually to the project for now.
