### ISSUE TITLE
Document Uploader:  Drag and Drop does not work in IE

### ISSUE THREAD

**Issue by mremigio** [box/box-ui-elements#557]
Please fill out the following template so we can reproduce and fix your issue as quickly as possible!

**Environment:**
- Elements version: 
https://cdn01.boxcdn.net/platform/elements/6.0.0/en-US/explorer.js
https://cdn01.boxcdn.net/platform/elements/6.0.0/en-US/explorer.css

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10]
Windows 10
Internet Explorer (IE)
11.547.16299.0

**Steps to reproduce the problem:**
1. From Content Explorer click on Upload
2. Once in Uploader, drag and drop files using IE (chrome, edge and firefox work)
3. Documents are not added

**What is the expected behavior? (Screenshots can be helpful here)**
Drag and drop via IE should work.  It worked in version 4.3

**What went wrong? (Screenshots, console logs, or HAR files can be helpful here)**
Documents not added when dragged and dropped via IE.  Chrome, Edge and Firefox work with drag and drog.

**Comment by cmuriyadan** [comment]
We are using Box Content explorer plugin in our JS based application and we are also facing the same issue. Request box to take a look at it and let us know if this can fixed

**Comment by mremigio** [comment]
Hi:
Any luck with this ?
Thank you

**Comment by stevebingsoo** [comment]
This problem still exists in UI Elements v11.0.2 and the latest beta v12.  I believe the cause of the problem is this [dropValidator] (https://github.com/box/box-ui-elements/blob/0b233b5aa4e07cfcc3e95f0812dadea8b459ca5f/src/elements/content-uploader/DroppableContent.js#L34)

Internet explorer's dataTransfer.types property does not return a string array like other browsers.  Instead, it returns a DOMStringList.  As a result, the dropValidator function should not use the Array.indexOf function for IE and should instead use the DOMStringList.contains function.
